### ISSUE TITLE
[tzatziki-logback] the log contains: ConcurrentModificationException

### ISSUE THREAD

**Issue by z06lsouc** [Decathlon/tzatziki#106]
ConcurrentModificationException while checking the logs:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.assertj.core.internal.Iterables.satisfiesCondition(Iterables.java:1384)
	at org.assertj.core.internal.Iterables.conditionIsSatisfiedAtLeastNTimes(Iterables.java:953)
	at org.assertj.core.internal.Iterables.assertAreAtLeast(Iterables.java:944)
	at org.assertj.core.api.AbstractIterableAssert.areAtLeast(AbstractIterableAssert.java:727)
	at com.decathlon.tzatziki.steps.LoggerSteps.lambda$the_logs_contain$7(LoggerSteps.java:142)
	at com.decathlon.tzatziki.steps.LoggerSteps.lambda$the_logs_contain$12(LoggerSteps.java:147)
	at com.decathlon.tzatziki.utils.Guard.in(Guard.java:50)
	at com.decathlon.tzatziki.utils.Guard$5.lambda$in$0(Guard.java:191)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at ?.within 10000ms the logs contains at least 3 lines equal to "?contains {{expectedLog}}"
```

AssertJ directly delegates any list assertion to java stream with filtering, therefore any concurrent modification of the list is not allowed. I've probably run into this because I'm testing a background process that will continue to log; thus logs may be added to the `ListAppender` while checking said appender if the test pipeline slows down enough.

Unfortunately the `ListAppender` comes from another lib (Semla) and uses internally an `ArrayList` which does not provide any thread safe way to iterate over it (either for direct check or copy).

**Comment by z06lsouc** [comment]
@mimfgg Would you be open to change Semla's `ListAppender` implementation to either use a threadsafe list or enforce a synchronization upon adding new line that could be shared by other classes ?

**Comment by mimfgg** [comment]
Hi! Sure :)

**Comment by mimfgg** [comment]
v1.2.2 released, it should be on maven central in a couple of hours.

**Comment by z06lsouc** [comment]
Thx :) From what I see of the change in Semla I'll offer a PR with the required synchronization

**Comment by mimfgg** [comment]
you wanted more than that: https://github.com/mimfgg/semla/commit/41bae8fc6864174218ce41dbe8baf0e5f7aa224f ?

**Comment by z06lsouc** [comment]
Well. With the implementation/wrapper chosen only the original `List`'s methods are thread safe, but not the objects returned by said `List`, like the iterator. But either though plain synchronization or some `List` methods that are now synchronised it is possible to make the assertion thread safe.

**Comment by mimfgg** [comment]
yeah, you will have to synchronize on the list if you want to iterate of it. Otherwise we should have switch to a BlockingQueue or something like that.

You can still create your own Appender if you want something else and configure the logger to use it if that's not enough, it should be fairly easy ...

**Comment by z06lsouc** [comment]
Like I said, nonetheless it's more than possible with your change. I'll create a pull request as soon as the lib is published. I already prepared the code based on your implementation (but still quite generic in the approach )
