### ISSUE TITLE
Can't run tests in case of none web application

### ISSUE THREAD

**Issue by ibrahimhammanid** [Decathlon/tzatziki#151]
Hi all,

I'm working a spring boot none web application, when I try to use tzatziki I have the below error:
```shell
Caused by: io.cucumber.core.backend.CucumberBackendException: Error creating bean with name 'com.decathlon.tzatziki.steps.SpringJPASteps': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'com.decathlon.tzatziki.steps.SpringSteps': Unsatisfied dependency expressed through field 'localServerPort': Failed to convert value of type 'java.lang.String' to required type 'int'; For input string: "${local.server.port}"
	at io.cucumber.spring.SpringFactory.getInstance(SpringFactory.java:137)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
```

It seems that SpringSteps tries to use the local port regardless of the type of the application

**Comment by brian-mulier** [comment]
Hello, it is a known issue which is described in #100
Can you add your comment to this issue ? We have to put out these requirements...

**Comment by ibrahimhammanid** [comment]
I need to close this issue then?

**Comment by brian-mulier** [comment]
Sure
