### ISSUE TITLE
ConcurrentModificationException on the Utils.Time.typeAdapters Map

### ISSUE THREAD

**Issue by chrisnad** [Decathlon/tzatziki#167]
I am getting a `ConcurrentModificationException` while running tests in parallel where I often call `ObjectSteps.resolve` with formatted date patterns needing to be parsed:
```
[ERROR] com.decathlon.vct.vcstream.blackbox.CucumberTest.runScenario["receive a RETAILSTOCKPICTURES message", "VCStream Inbound Process - retailstockpictures"](1) -- Time elapsed: 1.252 s <<< FAILURE!
com.github.jknack.handlebars.HandlebarsException: 
inline@497950c3:1:9: java.util.ConcurrentModificationException
    inline@497950c3:1:9
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
        at com.decathlon.tzatziki.utils.Time.getTypeAdapter(Time.java:72)
        at com.decathlon.tzatziki.utils.Time.parse(Time.java:66)
        at com.decathlon.tzatziki.steps.ObjectSteps.lambda$new$19(ObjectSteps.java:173)
        ...
```

This is happening very consistently on every parallel run, my custom step is not very complicated and I just call something like `Mapper.toJson(objects.resolve(unresolvedContent))` and it works perfectly when run serially. Am I writing my tests wrong? otherwise I suggest the following:

change the Map implementation for typeAdapters from `LinkedHashMap` to `ConcurrentHashMap`

**Comment by chrisnad** [comment]
I came to the conclusion that resolving date patterns in a parallel environment is trickier than I anticipated, I solved mine by having the pattern calculated in a before step, this way I can use it as an input (in a @Given step) of my system under test, and have it as an expected outcome (@Then step)
